pip install asyncio
pip install beautifulsoup4
pip install colorama
pip install discord.py-self==1.9.2
pip install eel
pip install plyer
pip install mailtm
pip install pypresence
pip install pillow